name: recycling_helper
description: A recycling helper app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: 1.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  google_fonts: 6.2.1
  go_router: ^13.0.1
  shared_preferences: ^2.2.2
  camera: ^0.11.1
  image_picker: ^1.0.4
  flutter_tts: ^4.0.0
  image: ^4.5.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false     # iOS는 지금 안 쓸 거면 false
  image_path: "assets/images/flutter_icon.png"   # 아이콘 이미지 경로

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600